name: EverPhotoCheckin

on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'
    # 22:30 UTC => 06:30 Beijing

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout actions
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: pip install requests

    - name: Run
      run: |
        python EverPhotoCheckin.py
      env: 
        data: ${{secrets.DATA}}
        headers: ${{secrets.HEADERS}}
